name: PostgresOnDocker
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: Test1234=
    ports:
      - 5432:5432 
  adminer:
    depends_on:
      - postgres
    image: adminer
    ports:
      - 8080:8080